environment:

  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: src tests README.rst
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\01_example_simple_state_to_state.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\02_example_lambda_system_rwa_complex_pulse.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\03_example_lambda_system_rwa_non_hermitian.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\04_example_dissipative_qubit_reset.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\05_example_transmon_xgate.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\06_example_3states.ipynb
      # the following notebook currently do not run correctly on Windows
      #- PYTHON: "C:\\Python36"
      #  PYTHON_VERSION: 3.6
      #  TOXENV: py36-test
      #  TOTEST: docs\notebooks\07_example_PE.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\08_example_ensemble.ipynb
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      TOXENV: py36-test
      TOTEST: docs\notebooks\09_example_numpy.ipynb

install:
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -m pip install tox"
  - "%PYTHON%\\python.exe -m pip install coveralls"
  - "%PYTHON%\\python.exe -m pip freeze"
  - C:\Miniconda3\\Scripts\\activate"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -c tox-conda.ini -vv -e %TOXENV% -- %TOTEST%"
