# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
  global:
    # Doctr deploy key for qucontrol/krotov
    - secure: "GMn30DUTZh2SvIvFu9HSGEZRy0y6JyOJ3wl7iM2ykV9aXbe3QkgE+rREnrPqsgcT15rj0CQLpOuCEWspiwqiEL1suokOGDjBRXoyMXHYy7WFRxP7dfFxQzuquN2rW8wS+MLJhQRRBJBoLopsRZioREelDxWUbqOCSKO9PXQA2oWl1i9XeqriXG9w5/jH74A8WeV+wL9uJ/+RPZoHjU+oCQ9Ri9ad3FYJCThqxIAFCMiKx2gMrxJlmU3kgRJulh6fyL8YK3dNV9132o5SElzVAtoe0pNNphIJx6UyqGBKctazXyPr+mlLokZw9tx6rg25bmc4XlRG46pqTP89wC8Xc7WBKxdJsYNksqgvxKZGt8vUenpDeYwvZMRbcukclHTskQbZFHJsXALhNnPe0APgrRK45aDL7++RBD8+BCjcMHQVd6qFd6UKCrs2etTXkI5uTqQtJve7Pe8ofcTcN1BQwI9IlcZYveuMX8Tn5378+Lwxqbc92OSkGPYRp+uOjKiQXDZbdCCokcqL9OGyGh9TcEgSD1BNMT8ZlGFGtQ18oXnP70hhvm0UPEgk3FIRWFX2VRIeWlZX4UntUDiaIo65C9GSIO2lEqZL23SPm8z/vk5Jh20JFSYvRi/Llr0mORZQiZyY+b2ZaoYhQutnK3wNdA7IIhbfzxuh1wUCuxdtaBA="
matrix:
  fast_finish: true
  include:
    - name: Check codestyle
      python: 3.7
      env: TOTEST="" TOXENV="run-blackcheck,run-isortcheck" TRAVISCMD=""
    - name: Docs
      python: 3.7
      env: DOCS="true"
      addons:
        apt_packages:
          - pandoc
          - pandoc-citeproc
    - name: Python 3.5
      python: 3.5
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py35-test TRAVISCMD=""
    - name: Python 3.6
      python: 3.6
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py36-test TRAVISCMD=""
    - name: Python 3.7
      python: 3.7
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py37-test TRAVISCMD=""
    - name: Python 3.8-dev
      python: 3.8-dev
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py38dev-test TRAVISCMD=""
    - name: Notebook 1 (State-to-State)
      python: 3.7
      env: TOTEST=docs/notebooks/01_example_simple_state_to_state.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 2 (RWA)
      python: 3.7
      env: TOTEST=docs/notebooks/02_example_lambda_system_rwa_complex_pulse.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 3 (Non-Hermitian)
      python: 3.7
      env: TOTEST=docs/notebooks/03_example_lambda_system_rwa_non_hermitian.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 4 (Density Matrix)
      python: 3.7
      env: TOTEST=docs/notebooks/04_example_dissipative_qubit_reset.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 5 (Quantum Gate)
      python: 3.7
      env: TOTEST=docs/notebooks/05_example_transmon_xgate.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 6 (3 States)
      python: 3.7
      env: TOTEST=docs/notebooks/06_example_3states.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 7 (Perfect Entanglers)
      python: 3.7
      env: TOTEST=docs/notebooks/07_example_PE.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 8 (Ensemble Optimization)
      python: 3.7
      env: TOTEST=docs/notebooks/08_example_ensemble.ipynb TRAVISCMD=travis_wait TOXENV=py37-test TRAVISCMD=travis_wait
    - name: Notebook 9 (NumPy)
      python: 3.7
      env: TOTEST=docs/notebooks/09_example_numpy.ipynb TOXENV=py37-test TRAVISCMD=""
  allow_failures:
    - name: Python 3.8-dev
before_install:
    - sudo apt-get -y install liblapack-dev libblas-dev gfortran
install:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - travis_wait source .travis/texlive/texlive_install.sh
  - pip install tox
  - pip install codecov
  - pip install --upgrade cython
  - pip freeze
  - printenv
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  - set -e
  - if [[ "${TOXENV}" == "py38dev-test" ]]; then travis_wait 40 tox -c tox-pyenv.ini -e py38dev-runcmd -- python --version; fi
  - |
    if [[ "${DOCS}" == "true" ]]; then
      source .travis/docs.sh
    else
      $TRAVISCMD tox -c tox-pyenv.ini -e $TOXENV -- $TOTEST
    fi
  - echo "DONE"
after_success:
  - if [[ "${DOCS}" != "true" ]]; then codecov; fi
