name: py36
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - qutip
  - pip:
    - better-apidoc==0.3.1
    - sphinx-rtd-theme<0.3
    - sphinx_autodoc_typehints
    - sphinxcontrib-bibtex
    - sphinx-version-warning
    - nbsphinx<0.4
    - gitpython
