name: krotov
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - qutip=4.4.0
  - pip:
    - matplotlib
    - watermark
    - git+https://github.com/qucontrol/krotov.git@master#egg=krotov
